model:
  base_learning_rate: 4.5e-6  # Keeping this unchanged
  target: taming.models.vqgan.VQModel
  params:
    embed_dim: 4  # Updated to match
    n_embed: 16384  # Updated to match
    ddconfig:
      double_z: false  # Updated to match
      z_channels: 4  # Updated to match
      resolution: 256  # No change, already matches
      in_channels: 3  # No change, already matches
      out_ch: 3  # No change, already matches
      ch: 128  # No change, already matches
      ch_mult: [1, 2, 2, 4]  # Updated to match
      num_res_blocks: 2  # No change, already matches
      attn_resolutions: [32]  # Updated to match
      dropout: 0.0  # No change, already matches

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 10000
        disc_weight: 0.8
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 5
    num_workers: 8
    train:
      target: taming.data.custom.CustomTrain
      params:
        training_images_list_file: C:\Users\ammic\Desktop\ClariGAN-DL\xx_trainB.txt
        size: 256
    validation:
      target: taming.data.custom.CustomTest
      params:
        test_images_list_file: C:\Users\ammic\Desktop\ClariGAN-DL\xx_testB.txt
        size: 256

